apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pelican-cache.fullname" . }}-pelican-config
  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
data:
{{/*See note in deployment.yaml for why we have to change TlsCertificate and TlsKey*/}}
  pelican.yaml: |
    ---
    ConfigLocations:
      - "/usr/share/pelican/config.d"
      - "/etc/pelican/config.d"

    Cache:
      StorageLocation: /cache
      Port: {{ .Values.server.cachePort }}

    Server:
      WebPort: {{ .Values.server.webPort }}
      TlsCertificate: "/etc/pelican/cert-orig/tls.crt"
      TlsKey: "/etc/pelican/cert-orig/tls.key"

    Logging:
      LogLocation: "/var/log/pelican/pelican.log"

    Topology.DisableCacheX509: true

  50-instance.yaml: |
{{- include "pelican-cache.instanceConfig" . | nindent 4 }}
