apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pelican-cache.fullname" . }}-pelican-config
  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
data:
  config.yaml: |
    ---
    Cache:
      StorageLocation: /cache
      Port: {{ .Values.server.cachePort }}

    Federation:
      DiscoveryUrl: {{ .Values.federation.discoveryUrl | quote }}

    Server:
      WebPort: {{ .Values.server.webPort }}
{{/* We cannot mount the TLS secret at /etc/pelican/certificates because that
directory would become read-only and Pelican needs to write its own CA there.
So we mount it at cert-orig instead (see deployment.yaml). */}}
      TlsCertificate: "/etc/pelican/cert-orig/tls.crt"
      TlsKey: "/etc/pelican/cert-orig/tls.key"
      Hostname: {{ required "serverHostname is required" .Values.serverHostname | quote }}
    {{- if .Values.oidc.adminUsers }}
      UIAdminUsers:
        {{- toYaml .Values.oidc.adminUsers | nindent 8 }}
    {{- end }}
    {{- if .Values.webPassword.existingSecret }}
      UIPasswordFile: /etc/pelican/server-web-passwd
    {{- end }}

    {{- if .Values.cache.blocksToPrefetch }}
    Cache.BlocksToPrefetch: {{ .Values.cache.blocksToPrefetch }}
    {{- end }}
    {{- if .Values.oidc.enabled }}
    Cache.EnableOIDC: true
    {{- end }}
    {{- if .Values.lotman.enabled }}
    Cache.EnableLotman: true
    {{- end }}
    {{- if .Values.cache.highWaterMark }}
    Cache.HighWaterMark: {{ .Values.cache.highWaterMark }}
    {{- end }}
    {{- if .Values.cache.lowWaterMark }}
    Cache.LowWaterMark: {{ .Values.cache.lowWaterMark }}
    {{- end }}
    {{- if .Values.cache.filesMaxSize }}
    Cache.FilesMaxSize: {{ .Values.cache.filesMaxSize }}
    {{- end }}
    {{- if .Values.cache.filesNominalSize }}
    Cache.FilesNominalSize: {{ .Values.cache.filesNominalSize }}
    {{- end }}
    {{- if .Values.cache.filesBaseSize }}
    Cache.FilesBaseSize: {{ .Values.cache.filesBaseSize }}
    {{- end }}
    {{- if .Values.cache.concurrency }}
    Cache.Concurrency: {{ .Values.cache.concurrency }}
    {{- end }}

    {{- if .Values.oidc.enabled }}

    OIDC:
      ClientIDFile: /etc/pelican/oidc/client.id
      ClientSecretFile: /etc/pelican/oidc/client.secret
    {{- end }}

    Logging:
      LogLocation: "/var/log/pelican/pelican.log"
      Level: {{ .Values.logging.level | quote }}
    {{- if .Values.logging.cache }}
      Cache:
        {{- toYaml .Values.logging.cache | nindent 8 }}
    {{- end }}

    Topology.DisableCacheX509: true

    {{- if .Values.lotman.enabled }}

    Lotman:
      LotHome: /var/lib/pelican/lotman
    {{- end }}

    XrootD.Sitename: {{ required "sitename is required" .Values.sitename | quote }}
    {{- if .Values.xrootd.extraConfig }}
    XrootD.ConfigFile: /etc/pelican/xrootd.conf
    {{- end }}

    {{- if .Values.extraPelicanConfig }}

    {{ toYaml .Values.extraPelicanConfig }}
    {{- end }}
