{{- $pvcName := printf "%s-data" (include "pelican-cache.fullname" .) -}}
{{- $shouldRender := eq (include "pelican-cache.shouldRenderPvc" (dict "root" . "pvcName" $pvcName) | trim) "true" -}}
{{- if and (eq .Values.cache.storageType "pvc") $shouldRender }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
spec:
  {{- if .Values.cache.storageClassName }}
  storageClassName: {{ .Values.cache.storageClassName | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cache.pvcSize }}
{{- end }}
