{{- $pvcName := printf "%s-issuer-key" (include "pelican-cache.fullname" .) -}}
{{- $shouldRender := eq (include "pelican-cache.shouldRenderPvc" (dict "root" . "pvcName" $pvcName) | trim) "true" -}}
{{- if and (eq .Values.issuerKey.type "pvc") $shouldRender }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
spec:
  {{- if .Values.issuerKey.pvc.storageClass }}
  storageClassName: {{ .Values.issuerKey.pvc.storageClass | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.issuerKey.pvc.size }}
{{- end }}
